### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by kbirand** [teodorpatras/SideMenuController#1]
Thank you for a straight forward and clean solution. Can you direct me what to do for rotation recalculation of views.

Thanks.

**Comment by teodorpatras** [comment]
Thank you for your interest in this component. Unfortunately it is still in the beta phase and only works for portrait orientation. Support for other orientations will be available soon, in the next versions.

**Comment by kbirand** [comment]
Thank you for your prompt reply. looking forward for the new version.

**Comment by teodorpatras** [comment]
Orientation handling is now available. Sorry for the long delay. Cheers!
