### ISSUE TITLE
Side Menu Button While NavigationBar is Hidden

### ISSUE THREAD

**Issue by Nauman7222** [teodorpatras/SideMenuController#104]
how can i use side menu  with  Navigation Controller while NavigationBar is hidden?

**Comment by PeerLabs** [comment]
Allow me to take a punt here...

in your AppDelegate ...  configure your SideMenuController ...

SideMenuController.preferences.interaction.panningEnabled = true

**Comment by Nauman7222** [comment]
ok , and how can i configure custom button to show side menu ?

**Comment by Nauman7222** [comment]
In UIButton Action  sideMenuController?.toggle()  works for me.
