### ISSUE TITLE
NavigationBar overlap

### ISSUE THREAD

**Issue by Lyansun** [teodorpatras/SideMenuController#13]
I take a tabbar as the centerViewController,This tabbar contains three viewControllers 
`let vc1 = MicroStationController()
		vc1.title = "vc1"

		let nc1 = UINavigationController(rootViewController: vc1)

		let vc2 = MsgViewController()
		vc2.title = "vc2"
		let nc2 = UINavigationController(rootViewController: vc2)

		let vc3 = SearchController()
		vc3.title = "vc3"
		let nc3 = UINavigationController(rootViewController: vc3)

		let tabBarController = UITabBarController()
		tabBarController.viewControllers = [nc1, nc2, nc3]
		let nav = UINavigationController(rootViewController: tabBarController)
		self.sideMenuController?.embedSideController(LeftViewController())
		self.sideMenuController?.embedCenterController(nav)`
and then I can't see this three viewController's navigationItems

**Comment by teodorpatras** [comment]
can you post a screenshot?

**Comment by Lyansun** [comment]
![qq20160621-1 2x](https://cloud.githubusercontent.com/assets/17959642/16206277/3547b450-375a-11e6-865e-947cc43cebe6.png) can you see that?

**Comment by teodorpatras** [comment]
I cannot understand what is happening, and I cannot reproduce any issues based on your snippet. I have updated the example project. Please download it and see how the programmatic example is implemented. Best of luck :)

**Comment by Lyansun** [comment]
I have followed your example project, but it always be a hint of 'fatal error: unexpectedly found nil while unwrapping an Optional value' 
 sideViewController.view.frame = sidePanel.bounds
`  /**
     Embeds a new side controller
     
     - parameter controller: controller to be embedded
     */
    public func embedSideController(controller: UIViewController) {
        if sideViewController == nil {
            
            sideViewController = controller
            sideViewController.view.frame = sidePanel.bounds
            
            sidePanel.addSubview(sideViewController.view)
            
            addChildViewController(sideViewController)
            sideViewController.didMoveToParentViewController(self)
            
            sidePanel.hidden = true
        }
    }`

**Comment by Lyansun** [comment]
I updated the source file,the mistakes have disappeared, but my problem is still not solved. :(

**Comment by teodorpatras** [comment]
please upload a zip archive with an example project where you have this issue

**Comment by Lyansun** [comment]
You can take a look at your own example project, which is the issue 
![qq20160621-2 2x](https://cloud.githubusercontent.com/assets/17959642/16220544/21e7e39c-37c0-11e6-8234-91f6c8423162.png)

**Comment by teodorpatras** [comment]
Cool, so I had time to look into it and the problem makes sense: you add a navigation bar when you embed the tab controller and another when you put each view controller inside a navigation view controller inside the tab bar controller :) so, the solution is:

```
let sideMenuViewController = SideMenuController()

// create the view controllers for center containment
let vc1 = UIViewController()
vc1.view.backgroundColor = UIColor.redColor()
vc1.title = "first"
let nc1 = UINavigationController(rootViewController: vc1)
vc1.navigationItem.title = "first"

let vc2 = UIViewController()
vc2.view.backgroundColor = UIColor.yellowColor()
vc2.title = "second"
let nc2 = UINavigationController(rootViewController: vc2)
vc2.navigationItem.title = "second"

let vc3 = UIViewController()
vc3.view.backgroundColor = UIColor.blueColor()
vc3.title = "third"
let nc3 = UINavigationController(rootViewController: vc3)
vc3.navigationItem.title = "third"

let tabBarController = UITabBarController()
tabBarController.viewControllers = [nc1, nc2, nc3]

// create the side controller
let sideController = UITableViewController()

// embed the side and center controllers
sideMenuViewController.embed(sideViewController: sideController)
sideMenuViewController.embed(centerViewController: tabBarController)

// add the menu button to each view controller embedded in the tab bar controller
[nc1, nc2, nc3].forEach({ controller in
    controller.addSideMenuControlButton()
})
```

I have updated the Readme file and realsed a new version to Cocoapods & Carthage. Thanks for pointing this confusion out.

**Comment by Lyansun** [comment]
There is also a point, the overall gesture will affect other views of the gesture, such as CenterView has a panning gesture(like the TableViewCell left slide to show delete button), then the two gesture will conflict.My English is so bad, I hope you can understand what I mean. :)

**Comment by teodorpatras** [comment]
did you disable it? 

`sideMenuController?.preferences.drawing. panningEnabled = false`

**Comment by Lyansun** [comment]
I tried,but Xcode reminds me: "Value of type 'SideMenuController' has no member 'preferences' "  or did I do something wrong?

**Comment by teodorpatras** [comment]
yes, update to the latest version, for any other questions, please read the Readme file, it provides a lot of useful insight.

**Comment by Lyansun** [comment]
Although I do not want to say that you understand that, but still thank you, SideMenuController is very useful, I would like to recommend it to other developers,I am sorry that Github does not allow me to give you more Star:)

**Comment by teodorpatras** [comment]
Thanks for appreciation, feel free to recommend it to all your friends!
