### ISSUE TITLE
Module compiled with Swift 4.0 cannot be imported in Swift 4.0.2

### ISSUE THREAD

**Issue by EgorVeremeychik** [teodorpatras/SideMenuController#134]
Module compiled with Swift 4.0 cannot be imported in Swift 4.0.2. I use Xcode 9.1.

**Comment by frederic-adda** [comment]
You use Carthage, right ? 
Try deleting the "Carthage" directory of your project and rebuilding it with `carthage update`.

**Comment by EgorVeremeychik** [comment]
@frederic-adda Thanks! It work for me!
