### ISSUE TITLE
Sidebar layout iPhone X not full to bottom

### ISSUE THREAD

**Issue by StevenVerheyen** [teodorpatras/SideMenuController#136]
Hi!

I was investigating a lay-out issue that the sidemenu view is not displayed fully to the bottom of the application. Might this be misconfiguration or a bug in the framework?

This is only an issue with iPhone X.
Thanks in advance!

![screen shot 2017-11-25 at 11 07 09](https://user-images.githubusercontent.com/1708722/33229527-e1be953e-d1d0-11e7-899f-9a9cf4886dbb.png)

**Comment by StevenVerheyen** [comment]
Issue is fixed and in PR ready for merge here: [https://github.com/teodorpatras/SideMenuController/pull/137](url)

**Comment by justinlee** [comment]
Issue is fixed and PR ready for merge here: #146

**Comment by justinlee** [comment]
Issue is fixed and in PR ready for merge here: #146

**Comment by priyanshrajput** [comment]
This is not included in 0.2.4. How to get this update?

**Comment by priyanshrajput** [comment]
This is not included in 0.2.4. How to get this update?

**Comment by antonioreyna** [comment]
i have a similar problem but in my case the menu is at the bottom but showing a black space at the top
