### ISSUE TITLE
NavigationBar still overlap

### ISSUE THREAD

**Issue by Lyansun** [teodorpatras/SideMenuController#14]
:( But you didn't find that the same problem exists in your sample project.
![qq20160621-2 2x](https://cloud.githubusercontent.com/assets/17959642/16219323/0c66356c-37b8-11e6-9a57-e011bd000b4d.png)  Can you see the title("first") blocked by NavigationBar?

**Comment by teodorpatras** [comment]
can you make a zip archive and upload it here? I would like to see the issue because I cannot reproduce it

**Comment by teodorpatras** [comment]
issue closed, please reffer to #13
