### ISSUE TITLE
MenuBarButtonItem image and center shadow doesn't show up

### ISSUE THREAD

**Issue by jayrparro** [teodorpatras/SideMenuController#17]
Hi, 

Thanks for your work on this control and sharing it as open-source.
I've played around on this stuff and I'm stumbled with some issues. 

1. During the initial load, the `menuButtonImage` doesn't show up even the center ViewController is embedded with the UINavigationController.
Otherwise, I need to call `navigationController?.addSideMenuButton()` but it's redundant.

2. Setting-up the SideMenuController in AppDelegate doesn't have any effect. 
I've tried to modify some values but there's no effect (ex. centerPanelShadow, statusBehavior).

```
SideMenuController.preferences.drawing.menuButtonImage = UIImage(named: "menu")
SideMenuController.preferences.drawing.sidePanelPosition = .OverCenterPanelLeft
SideMenuController.preferences.drawing.sidePanelWidth = 300
SideMenuController.preferences.drawing.centerPanelOverlayColor = UIColor.darkGrayColor()
SideMenuController.preferences.drawing.centerPanelShadow = true
SideMenuController.preferences.animating.statusBarBehaviour = .ShowUnderlay
```
Hope you can clarify, or maybe, I've missed something. Thanks.

Please check this video [link](https://dl.dropboxusercontent.com/u/12912452/temp/sidemenu-test.mov)
and attach test project: [TestSideMenuController.zip](https://github.com/teodorpatras/SideMenuController/files/355510/TestSideMenuController.zip)

**Comment by teodorpatras** [comment]
Hi,

For some reason, the `viewDidLoad` of your custom `SideMenuController` subclass gets called before `applicationDidFinishLaunching` from the `AppDelegate`. I couldn't find why this weird behaviour is happening but basically, this means that the `SideMenuController` is fully configured before the preferences are applied in `applicationDidFinishLaunching` and therefore, those preferences have no effect. I suggest you move the customisation code somewhere it is executed before the initialisation of the `SideMenuController` subclass. One example could be:

```
class CustomMenuController: SideMenuController {

    required init?(coder aDecoder: NSCoder) {
        SideMenuController.preferences.drawing.menuButtonImage = UIImage(named: "menu")!
        SideMenuController.preferences.drawing.sidePanelPosition = .UnderCenterPanelLeft
        SideMenuController.preferences.drawing.sidePanelWidth = 300
        SideMenuController.preferences.drawing.centerPanelOverlayColor = UIColor.darkGrayColor()
        SideMenuController.preferences.drawing.centerPanelShadow = true
        SideMenuController.preferences.animating.statusBarBehaviour = .ShowUnderlay
        super.init(coder: aDecoder)
    }
}
```
By the way, if you figure out why `applicationDidFinishLaunching` is called after `viewDidLoad` let me know in the comments.

**Comment by jayrparro** [comment]
Hi, 

It happens when you use Storyboard and you set the custom `SideMenuController` as the initial view controller. The main nib file is loaded first, setup the SideMenuController and then, it call after the application app delegate `didFinishLaunchingWithOptions`.
So, setting up the SideMenuController in app delegates has no effect anymore.

The workaround I've done is to remove the initial view controller in Storyboard and invoke it by code in app delegate `didFinishLaunchingWithOptions`.

```
func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        
        application.applicationSupportsShakeToEdit = true
        // Override point for customization after application launch.
        
        SideMenuController.preferences.drawing.menuButtonImage = UIImage(named: "menu")
        SideMenuController.preferences.drawing.sidePanelPosition = .UnderCenterPanelLeft
        SideMenuController.preferences.drawing.sidePanelWidth = 300
        SideMenuController.preferences.drawing.centerPanelShadow = true
        SideMenuController.preferences.animating.statusBarBehaviour = .HorizontalPan
        SideMenuController.preferences.animating.transitionAnimator = CircleMaskAnimator.self
        
        self.window = UIWindow(frame: UIScreen.mainScreen().bounds)
        let mainStoryboard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
        let customSideMenuController = mainStoryboard.instantiateViewControllerWithIdentifier("CustomSideMenuId") as! CustomSideMenuController
        
        self.window?.rootViewController = customSideMenuController        
        self.window?.makeKeyAndVisible()
        
        return true
    }
```
