### ISSUE TITLE
 SideMenuController.preferences.drawing.sidePanelWidth = 300

### ISSUE THREAD

**Issue by zhaoyunyi** [teodorpatras/SideMenuController#19]
setup  SideMenuController.preferences.drawing.sidePanelWidth = 300 ,not userful for me?
use storyboard  change init ViewController ,  it will unuse

**Comment by teodorpatras** [comment]
Sorry man, I don't understand your english

**Comment by zhaoyunyi** [comment]
i'm so sorry for that ,but i find some problem when i use the storyboard  directly to my program, but now, it's fine, if you have time to discuss, we can change email, also can prove my english. 
![a](https://cloud.githubusercontent.com/assets/8953791/16895187/70497ffc-4ba0-11e6-888d-3cfc05e2882e.png) it can make  'SideMenuController.preferences.drawing.sidePanelWidth = 300' useful, that i can setup the width.  

![b](https://cloud.githubusercontent.com/assets/8953791/16895193/91c256fe-4ba0-11e6-9cc9-1cc4c2fc0adb.png) it's the other way that make it useless, you can try it, if have something, please tell me.

anyway ,thank you!

**Comment by teodorpatras** [comment]
I still don't understand what the issue is.
