### ISSUE TITLE
Navigation bar with back and menu button

### ISSUE THREAD

**Issue by rary44** [teodorpatras/SideMenuController#20]
Hello ,

[SlideMenu 3.zip](https://github.com/teodorpatras/SideMenuController/files/367723/SlideMenu.3.zip)

as shown in the project attached i want to move from home to second and third view controller 
the problem is i try to navigate to them by push and i only get back button without menu button and i try to navigate to it using present and sideMenuController?.embedCenterController() but i only get the menu button 

How can i get them both ?

Regards

**Comment by teodorpatras** [comment]
You need to add both manually. Have a look here: https://developer.apple.com/library/ios/documentation/UIKit/Reference/UINavigationItem_Class/index.html#//apple_ref/occ/instp/UINavigationItem/leftBarButtonItems

**Comment by mvoccola** [comment]
Is any more specificity available? How and where should one go about adding them both back in? I would like the back button in its normal location with the menu button immediately to the right.
