### ISSUE TITLE
Trouble with presentViewController

### ISSUE THREAD

**Issue by Stan92** [teodorpatras/SideMenuController#22]
Hi,
I have a problem when I use a presentViewController..
Here's my case..
I have 2 centerViewControllers (let's say A and B).
From A, I can launch a presentViewController.

1st case :
When I launch the presentViewController from A, at first time, everything is perfect. It fills all the screen.
When I show B and back to A and launch the presentViewController, I have a 20px padding that appears at the bottom (Like if the y of the presentViewController was -20px)

2nd case :
When I show B then show A and launch the presentViewController, I have the 20px padding at the bottom  (Like if the y of the presentViewController was -20px)

Any help?

EDIT.
FYI. : the statusBarBehaviour property was set to .SlideAnimation
Seems to work when it sets to .ShowUnderlay

**Comment by teodorpatras** [comment]
Can you make a demo project where you reproduce the issues and upload the zip here?

**Comment by teodorpatras** [comment]
Or if you can reproduce it in main example project, make a screen capture.

**Comment by Stan92** [comment]
Here's the file..
Take into account that I've changed your plist file (set View controller-based status bar appearance to YES)
and I've changed the statusBarBehaviour to SlideAnimation

From the "Center Controller 3", I've added a button "Press" that launches the Modal.

[SideMenuController-master.zip](https://github.com/teodorpatras/SideMenuController/files/370140/SideMenuController-master.zip)

**Comment by teodorpatras** [comment]
fixed in latest version
