### ISSUE TITLE
SideMenuController custom preferences don't take effect 

### ISSUE THREAD

**Issue by ahsas-sharma** [teodorpatras/SideMenuController#24]
First of all, thank you so much for sharing such a neatly designed Side Menu.  I'm relatively new to iOS Development so this helped a lot. Not sure where to get clarification so I'm opening an issue.

Referring to the Example project, I added the following code to AppDelegate's didFinishLaunchingWithOptions method - 
```
SideMenuController.preferences.drawing.menuButtonImage = UIImage(named: "Menu")
SideMenuController.preferences.drawing.sidePanelPosition = .OverCenterPanelLeft
SideMenuController.preferences.drawing.sidePanelWidth = 150
SideMenuController.preferences.drawing.centerPanelShadow = true
SideMenuController.preferences.animating.statusBarBehaviour = .ShowUnderlay
```

But changing the values of these properties doesn't seem to change anything on execution. It works fine in the Example project but not in my implementation. Any ideas on what I could possibly be doing wrong?

**Comment by teodorpatras** [comment]
Most probably the `SideMenuController` gets instantiated from the storyboard before the AppDelegate calls that methods to apply the preferences. I suggest you override the initializer `init(withCoder:)` and apply the preferences there so they get set before the `SideMenuController` gets created.

**Comment by ahsas-sharma** [comment]
You're right, that's exactly what's causing the issue. Could you tell me where/how exactly can I override the initializer? I integrated the framework using Cocoapods. Do I need to make the changes inside SideMenuController.swift file(it is locked for editing)?

In my current use case, I need to change the Interaction preferences in multiple view controllers since I want to disable the Pan/Swiping on certain screens. 

Your help is much appreciated!
