### ISSUE TITLE
Pass data from one view to another

### ISSUE THREAD

**Issue by mobinzk** [teodorpatras/SideMenuController#25]
Is there anyway I can pass data via performSegueWithIdentifier?
So I use storyboard and 
`sideMenuController?.performSegueWithIdentifier(DefinedSegueId, sender: nil)`
To segue to a different view

**Comment by mobinzk** [comment]
Just to update you on this I've created a singleton class and stored the data I would like to pass in that and then reading them in viewDidLoad.

**Comment by antonioreyna** [comment]
You can pass an object with that data to the sender
