### ISSUE TITLE
swipingEnabled does not work with UnderCenterPanel position

### ISSUE THREAD

**Issue by FouadRaheb** [teodorpatras/SideMenuController#27]
Swiping on tableView cells does not work when `sidePanelPosition ` is set to either `UnderCenterPanelLeft` or `UnderCenterPanelRight `. I have `swipingEnabled` set to true.

**Comment by teodorpatras** [comment]
`swipingEnabled` is only for `OverCenterPanelRight` or `UnderCenterPanelRight`. For the positions you wrote above, you have panning, which is based on a `UIScreenEdgePanGestureRecognizer`so this means you have to pan from the edge of the screen. For further details, please check the Readme file.

**Comment by FouadRaheb** [comment]
Is it possible to have panning enabled so I can swipe to show left menu and have tableView cells swipe to delete correctly? It is 2 opposite swipe directions.
