### ISSUE TITLE
Shadow of center panel not working when opening menu via button

### ISSUE THREAD

**Issue by daniel-mohemian** [teodorpatras/SideMenuController#29]
Hi there. Great side menu especially the control over the status bar is very nice to have 😃 .

However, I noticed that if the shadow of the center panel is activated, the shadow only seems to be drawn if the side menu is opened via the pan gesture from the edge of the screen. If the side menu is opened via the menu button, the shadow isn't drawn. I'll attach screenshots of the example project for clarification.

*Shadow drawn when opened with pan gesture*
![screen shot 2016-07-27 at 13 35 41](https://cloud.githubusercontent.com/assets/17877496/17174239/563b2bac-5400-11e6-875b-f1652b45f396.png)

*Shadow not drawn when opened via menu button*
![screen shot 2016-07-27 at 13 35 32](https://cloud.githubusercontent.com/assets/17877496/17174264/80c613d2-5400-11e6-89d5-3a249c58eb83.png)

#17 Also mentions shadow issues but it seems to be another issue.

**Comment by teodorpatras** [comment]
Thanks for pointing this out! Gonna fix it in the next release.

**Comment by combi83** [comment]
I notice the problem too...let me know if you can fix it 
Thank you

**Comment by teodorpatras** [comment]
will fix this by the end of the month, atm I have my hands quite full

**Comment by antonioreyna** [comment]
I got this problem too, thanks!

**Comment by teodorpatras** [comment]
Fixed in version `0.1.6`
