### ISSUE TITLE
swip in table view to add action some issues  solve this by    centerPanel.removeGestureRecognizer(panRecognizer)      and then centerPanel.addGestureRecognizer(panRecognizer)

### ISSUE THREAD

**Issue by OmarTawashi** [teodorpatras/SideMenuController#3]
swip in table view to add action some issues solve this by centerPanel.removeGestureRecognizer(panRecognizer) and then centerPanel.addGestureRecognizer(panRecognizer)

**Comment by teodorpatras** [comment]
sorry, I don't understand you.
