### ISSUE TITLE
Hiding or Locking SideMenu in some cases?

### ISSUE THREAD

**Issue by Bgen** [teodorpatras/SideMenuController#31]
How can I hide sidemenu or remove after embedded? 
In some cases, I need to close sidemenu. I couldn't change menu "sidePanelVisible" or embed a sidemenucontroller : nil,

**Comment by teodorpatras** [comment]
call `sidemenuController.toggle()` and it will hide the menu if it is visible or show it if it is hidden

**Comment by Bgen** [comment]
Actually, I'm asking to lock sidemenu for some cases. I'm not asking show or hide feature.

For instance, if a user is not logged in, he / she will not see the sidemenu or after log out she/ he will not see it, but in logged mode, the user can use sidemenu. In my case, if a user drag the page left to right, he / she can see sidemenu. I want to lock it.  

Thanks in advance.

**Comment by teodorpatras** [comment]
Did you have a look at [this](https://github.com/teodorpatras/SideMenuController#customisation)?

**Comment by lwinged** [comment]
Is it possible to have a completion handler in toggle function instead of using delegation ? I want to handle just one case. 

I don't want to do my task in hide/reveal functions delegate because it call at every hide/reveal events.

Maybe we could have open / close functions with completion ? 

What do you think about it ?

**Comment by teodorpatras** [comment]
can you make a pull request for that? @lwinged

**Comment by lwinged** [comment]
I did something like that : 

 ```
//Can't use "toggle" name because of :
//UIKitExtension -> button.addTarget(sideMenuController, action: #selector(SideMenuController.toggle), forControlEvents: UIControlEvents.TouchUpInside)
//Crash on completion?() -> animate(toReveal:)
public func togglePanel(completion: ((Void) -> (Void))? = nil) {
        
        if sidePanelVisible {
            close(completion)
        } else {
            open(completion)
        }
    }
    
    public func close(completion: ((Void) -> (Void))? = nil) {
        if !transitionInProgress {
            animate(toReveal: false, completion: completion)
        }
    }
    
    public func open(completion: ((Void) -> (Void))? = nil) {
        if !transitionInProgress {

            if !sidePanelVisible {
                prepare(sidePanelForDisplay: true)
            }
            
            animate(toReveal: true, completion: completion)
        }
    }

   // MARK: - Interaction -

//here : add completion handler
 func animate(toReveal reveal: Bool, completion: ((Void) -> (Void))? = nil){
        
        transitionInProgress = true
        sidePanelVisible = reveal
        
        if reveal {
            set(statusBarHidden: reveal)
        }
        
        let setFunction = sidePanelPosition.isPositionedUnder ? setUnderSidePanel : setAboveSidePanel
        setFunction(hidden: !reveal) { updated in
            if !reveal {
                self.prepare(sidePanelForDisplay: false)
                self.set(statusBarHidden: reveal)
            }
            self.transitionInProgress = false
            self.centerViewController.view.userInteractionEnabled = !reveal
            if updated {
                let delegateMethod = reveal ? self.delegate?.sideMenuControllerDidReveal :       self.delegate?.sideMenuControllerDidHide
                delegateMethod?(self)
               //here : execute completion 
                completion?()
            }
        }
    }

```

What do you think about that ?

**Comment by teodorpatras** [comment]
I don't understand the crash behind using `toggle`

**Comment by lwinged** [comment]
I can't replace your toggle function by mine (togglePanel -> need a rename) 

here :
`//UIKitExtension -> button.addTarget(sideMenuController, action: #selector(SideMenuController.toggle), forControlEvents: UIControlEvents.TouchUpInside)`

Actually, I think the selector send a parameter not nil I don't know why and inside animate function the execution of completion?() crash with EXC_BAD_ACCESS.

So I didn't change your toggle function but I added mine (togglePanel)

Open & Close functions seem to work.

TogglePanel works too but I don't listen this function like your toggle function :
`//UIKitExtension -> button.addTarget(sideMenuController, action: #selector(SideMenuController.toggle), forControlEvents: UIControlEvents.TouchUpInside)`

**Comment by antonioreyna** [comment]
how did you manage to avoid the menu when not logged? I think i want to get something similar so when user is not logged, the menu is not shown also no swipe to open menu.

**Comment by Isuru-Nanayakkara** [comment]
I too think this is a good addition to have. A simple way to enable/disable menu button would be nice.
