### ISSUE TITLE
Custom Preferences lost

### ISSUE THREAD

**Issue by antonioreyna** [teodorpatras/SideMenuController#33]
So for the custom preferences to work, should i call them on the wrapper class instead of the app delegate like this?

```
class MenuWrapperViewController: SideMenuController {
    
    required init?(coder aDecoder: NSCoder) {
        // Configuración del menu
        SideMenuController.preferences.drawing.menuButtonImage = UIImage(named: "hamburguer");
        SideMenuController.preferences.drawing.sidePanelPosition = .UnderCenterPanelLeft;
        SideMenuController.preferences.drawing.sidePanelWidth = 300;
        SideMenuController.preferences.drawing.centerPanelShadow = true;
        SideMenuController.preferences.animating.statusBarBehaviour = .ShowUnderlay;
        super.init(coder: aDecoder);
    }
```

I notice that if i call first the `super.init` they doesn't work either.

Thanks.

**Comment by teodorpatras** [comment]
Yes, for some reason, sometimes if the initial view controller in your storyboard is the side menu controller, it's `init(..)` is called before the AppDelegate `didFinishLaunching`. Will update the readme asap.

**Comment by iosBeappTeam** [comment]
Hello, there is a real issue for this feature i think. 
When i print the "SideMenuViewController.preference" that totally different than the self.preference. 
I will send you a PR with my solution in some days.

Ah and yes, thanks for your work this library is really great :)
