### ISSUE TITLE
Weird behavior when using SideMenuController subclass as initial view controller

### ISSUE THREAD

**Issue by frederic-adda** [teodorpatras/SideMenuController#35]
Hi,

I wanted to use the SideMenuController as the initial view controller in my app.
The behavior is really weird in that case.

As I thought there was something wrong with my code, I tried to use your example project, and set the CustomSideMenuController as the initial view controller.
In that case, there is no button.
And if I try to drag the side menu, it does not respect the width set in the App Delegate, and "pushes" the CenterVC instead of going over it.

![simulator screen shot 22 aout 2016 16 03 02](https://cloud.githubusercontent.com/assets/17590846/17857419/f76f054e-6881-11e6-8dec-56a797447509.png)

![simulator screen shot 22 aout 2016 16 01 02](https://cloud.githubusercontent.com/assets/17590846/17857421/faf82358-6881-11e6-9af2-8b24bd21d0ca.png)

Let me know if you can fix that or if I have to check with another project (I would prefer the first solution because I like yours better).

Thanks
Fred

**Comment by teodorpatras** [comment]
fixed in version `0.1.6`. Checkout the revised `ReadMe` file.

**Comment by frederic-adda** [comment]
Very cool ! Works like a charm, thanks for your reactivity !
