### ISSUE TITLE
can i use multiple side menu?

### ISSUE THREAD

**Issue by choiks14** [teodorpatras/SideMenuController#37]
i want to use multiple sidemenu.

if user has not session, use A sidemenu controller
other case,use B sidemenu controller.

is it possible?

**Comment by teodorpatras** [comment]
two side menus at the same time?

**Comment by choiks14** [comment]
no i want to change sidemenu dynamically

please help me.

**Comment by teodorpatras** [comment]
it's like any other view controller, there's nothing special about it... imagine you would exchange a tab bar controller or a navigation controller
