### ISSUE TITLE
embed doesn't me work

### ISSUE THREAD

**Issue by atapias** [teodorpatras/SideMenuController#40]
Hi, I'm trying SideMenuController but not working properly embedded mode.

When I select an item from the side menu, the new view controller is loaded full screen. Not load embedded in the center. Therefore, the side menu button disappears, but if I slide from left to right,  menu appears.

This is my code in MenuController:

`func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {`
`if let index = previousIndex {`
`tableView.deselectRowAtIndexPath(index, animated: true)`
`}`
`let listadoCentrosController:ListadoCentrosController = self.storyboard?.instantiateViewControllerWithIdentifier("centrosVC") as! ListadoCentrosController`
`sideMenuController?.embed(centerViewController: listadoCentrosController, cacheIdentifier: nil)`
`previousIndex = indexPath`

![captura de pantalla 2016-09-08 a las 10 59 14](https://cloud.githubusercontent.com/assets/20042160/18344057/19e3e61c-75b6-11e6-9422-5852329c980f.png)

![captura de pantalla 2016-09-08 a las 10 59 21](https://cloud.githubusercontent.com/assets/20042160/18344063/218a0126-75b6-11e6-97c1-1cece49ab26a.png)

![captura de pantalla 2016-09-08 a las 10 59 32](https://cloud.githubusercontent.com/assets/20042160/18344074/2936a712-75b6-11e6-92db-b69a6fdd2d78.png)

Someone knows I'm doing wrong?

Thank you very much

**Comment by teodorpatras** [comment]
can you attach a demo xcode project?

**Comment by atapias** [comment]
Hi again!

I attached the demo

I have 2 viewcontrollers, FirstViewController (initial) and SecondViewController for this example.

Thank you very much @teodorpatras 

[elha-ios-copia.zip](https://github.com/teodorpatras/SideMenuController/files/461351/elha-ios-copia.zip)

**Comment by teodorpatras** [comment]
When you embed the center view controller, if you want it to have the navigation bar onto which a menu button will be put, the controller needs to be a `UINavigationController` right? If there's no navigation controller, you can still embed it but there won't be any menu button because there is no navigation bar.

change

```
sideMenuController?.embed(centerViewController: listadoCentrosController)
```

to

```
sideMenuController?.embed(centerViewController: UINavigationController(rootViewController: listadoCentrosController)))``
```

**Comment by atapias** [comment]
@teodorpatras thank you so much!!

I not take long for iOS programming. It's a pleasure to meet people like you.

Congratulations for SideMenuController, it is a great control !!

regards
