### ISSUE TITLE
Side menu not recognizes gestures in Xcode8 release

### ISSUE THREAD

**Issue by FNet92** [teodorpatras/SideMenuController#43]
I recently updated to xcode8 release, but side menu not recognizes gestures anymore. It doesn't opens, does not closes menu anymore by swiping

**Comment by teodorpatras** [comment]
There seems to be an issue with iPhone 7 simulator, the others before 7 work just fine. Are you testing on simulator or on device? If device, then which one is it?

**Comment by FNet92** [comment]
I've tested on a real device iPad 2 (the old one, iOS 9.5) and iPhone 5s simulator (iOS 9.3)

**Comment by FNet92** [comment]
btw, the problem only with underCenterPanelRight mode
with overCenterPanelLeft everything works fine

**Comment by teodorpatras** [comment]
First of all, for underCenterPanel there is no swiping. There is only panning, which has to start from the edge of the screen to be recognised.

**Comment by FNet92** [comment]
oh. But before Xcode 8 release I could just start panning from the middle of the screen to open side menu underCenterPanel. By panning, which has to start from the edge of the screen I could go to the previous ViewController (by default in Storyboard). 

Isn't it available anymore?
