### ISSUE TITLE
iPhone 7 problem

### ISSUE THREAD

**Issue by Babelfisch** [teodorpatras/SideMenuController#46]
If I test the demo in Xcode 8 and iPhone 7 (or 7 plus) simulator, the center view controller will be white colored (or invisible) while the side menu is shown. This happens only on iPhone 7 simulator but not on iPhone 6 or iPad.

**Comment by teodorpatras** [comment]
does this happen on a real device? There's a simulator issue with the `UIScreen`'s `snapshotViewAfterScreenUpdates`
