### ISSUE TITLE
Example not runable

### ISSUE THREAD

**Issue by StuartMorris0** [teodorpatras/SideMenuController#47]
Hello,

How do you get the example project to work? I've downloaded the zip but it does not build, there is no podfile included so not sure if one needed to be added. Looked like it was all included as source so thought it would just run/build.

Thanks

**Comment by teodorpatras** [comment]
What errors do you get when trying to build?

**Comment by StuartMorris0** [comment]
There is a ton.
![screen shot 2016-09-26 at 09 36 54](https://cloud.githubusercontent.com/assets/1994135/18827858/dc1e6c38-83cc-11e6-8f56-78485121a66b.png)

**Comment by teodorpatras** [comment]
I don't know your setup but that looks like it's trying to compile under Swift 2.x. The example on master branch (pod/carthage `v0.2.0`) is made for Xcode 8.0/Swift 3.0.

**Comment by StuartMorris0** [comment]
You are right it builds fine with Xcode8. I assumed like most it was not ready but you are ahead of the game 🙌🏽

Do you know which version is Swift 2.x compatible?

**Comment by teodorpatras** [comment]
`v0.1.6` :)
