### ISSUE TITLE
Push segue from center VC fired from Side menu

### ISSUE THREAD

**Issue by ompagi** [teodorpatras/SideMenuController#48]
So i have a storyboard as follow :

![screen shot 2016-09-26 at 1 28 30 pm](https://cloud.githubusercontent.com/assets/21188799/18824615/a14deef0-83ed-11e6-9700-f53ba42eae3f.png)

There is a button in my side menu that will perform a push segue from VC 3 which is the center VC of the sidemenucontroller to a soon-to-be-made VC beside VC 3, so that the nav-bar of the VC "5" will have a back button to navigate back to the center VC. How does one implement this?

**Comment by Ki1L3r** [comment]
I have a very similar issue as you, I have the same login button, and I want to make a transition from VC3 to my LoginViewController. From the SideMenu I'm trying to make this, but It doesnt work:

```
let loginViewController = LoginViewController(nibName: Constants.VC.LOGIN, bundle: nil)
self.sideMenuController?.centerViewController.navigationController?.pushViewController(loginViewController, animated: true)
```

**Comment by Ki1L3r** [comment]
I have been researching And I tried to override embeed funtion in order to set a new variable for the centerViewController, but It has to be open to override it... I have subclased it and I have a new centerController that I set it when embed is called, now It makes the transition, could be a library bug?

**Comment by Ki1L3r** [comment]
@teodorpatras any suggestion please ?

**Comment by teodorpatras** [comment]
First of all, the side panel should be used only to make transitions that concert the SideMenuController as a whole. If you want to make transitions within the center view controller, the side panel shouldn't be concerned about it.

If you want a login, you can present a view controller on top of the whole hierarchy.

@Ki1L3r this doesn't look right: `self.sideMenuController?.centerViewController.navigationController?.push...` center controller is the navigation controller

@ompagi I really don't understand your use case

**Comment by ompagi** [comment]
@teodorpatras in short, i want to call a push segue from VC3 by clicking on a button located in side drawer / side menu

**Comment by teodorpatras** [comment]
@ompagi you can do something like `self.sideMenuController?.centerViewController.push...`

**Comment by ompagi** [comment]
@teodorpatras Alright, thanks. It's safe to close now.
