### ISSUE TITLE
How to setting the OverlayColor?

### ISSUE THREAD

**Issue by Lyansun** [teodorpatras/SideMenuController#49]
how to setting the overlayColor when the panelPosition is .UnderCenterPanelLeft?

**Comment by teodorpatras** [comment]
In that case there is no overlay, please read the Readme file.

**Comment by Lyansun** [comment]
yes i knew,but i still need that,can you give me some advice?

**Comment by teodorpatras** [comment]
what kind of overlay do you need?

**Comment by Lyansun** [comment]
just like when the position is OverCenterPanel. Strictly  it is not overlay,I just need the centerPanelColor darken when sidePanel opened.
