### ISSUE TITLE
Presenting a view controller from the center view controller

### ISSUE THREAD

**Issue by StuartMorris0** [teodorpatras/SideMenuController#50]
Hello,

We have a setup where we have a UITableViewController (within a UINavigationController) as the centre view.

When a cell is tapped, we want to segue to another view controller like a normal Push segue. 

I have tried two different setups for this. One in the storyboard, standard hooking up a segue and calling it. Secondly, I tried instantiating the view controller programmatically and calling self.navigationController.presentViewControlller... But these do not display as expected. The first case always shows the controller with a modal/show detail style (not sure which). The presentViewController route replaces the stack entirely, strange.

Do you know how to push a controller with a normal push segue from a centre view controller? 

Thanks

**Comment by teodorpatras** [comment]
If the center view controller is a UINavigationController instance you should be able to just do `self.navigationController.presentViewController..`. It works, I remember I tested it before. Can you upload an example project? Maybe I see there what you did wrong. Cheers!

**Comment by StuartMorris0** [comment]
Closing the issue, setup a test project with Swift 2 and Swift 3 and both worked. Went back to the original project and reconfigured once again and it started working, strange. Thanks for your response.
