### ISSUE TITLE
Provide option to disabled button highlight adjustment

### ISSUE THREAD

**Issue by nodify-at** [teodorpatras/SideMenuController#52]
Hi,

it would be great if we can disable image highlight adjustment in addSideMenuButton() function.

A better way would be to get the button as a return value to change/improve it ourself.

E.g: func addSideMenuButton(options?)  {
     button.adjustsImageWhenHighlighted = false
}

**Comment by nodify-at** [comment]
See also my pull request : https://github.com/teodorpatras/SideMenuController/pull/53

**Comment by teodorpatras** [comment]
see my comment on #53
