### ISSUE TITLE
Status bar appears over menu controller after updating outlets in menu controller

### ISSUE THREAD

**Issue by frederic-adda** [teodorpatras/SideMenuController#56]
Hi

I'm using the library in one of my apps, and it's great!
I have encountered the following issue:
- in the SideMenuController delegate, I used `sideMenuControllerDidReveal` to update an Imageview
  
  ```
  extension RootViewController: SideMenuControllerDelegate {
  func sideMenuControllerDidReveal(sideMenuController: SideMenuController) {
      print(#function)
  
          if let menuController = sideMenuController.sideViewController as? MenuController {
          // FIXME: causes the status bar to appear above the side menu :-(
          // Update the profile
              menuController.updateProfile()
          }
      }
  }
  ```
- This method `updateProfile` is defined as so:
  
  ```
  func updateProfile() {
  // Update the user name and picture
  dispatch_async(dispatch_get_main_queue()) { 
          if let profile = UserAuth.currentUserProfile {
              self.userNameLabel.text = profile.name
              self.userImageView.sd_setImageWithURL(profile.picture, placeholderImage: UIImage(named: "user_m"))
          }
      }
  }
  ```

When that happens, the status bar goes OVER the side menu. Weird.

![simulator screen shot 14 oct 2016 a 17 08 19](https://cloud.githubusercontent.com/assets/17590846/19392383/da912186-9230-11e6-8399-85f1749ecd7d.png)

This does not happen if I comment this code.
![simulator screen shot 14 oct 2016 a 17 09 22](https://cloud.githubusercontent.com/assets/17590846/19392415/f7b5eb70-9230-11e6-95e2-e80c960549e8.png)

Thanks for your help

**Comment by teodorpatras** [comment]
there are various `StatusBarBehaviour` options you can choose. What you have there looks like `showUnderlay` check the other ones maybe they fit better for you.

**Comment by frederic-adda** [comment]
I used Horizontal Pan.
But I find it weird that the appearance changes depending on whether or not I update the UI in the side menu.

**Comment by ugenlik** [comment]
Can we re-open this issue?  Something similar happening in my app too, if I change `appDelegate.window?.rootViewController` in the app, status bar is visible even though I make sure I use `.showUnderlay`
