### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Stan92** [teodorpatras/SideMenuController#58]
Hi,
I m trying to use your library using pod.
During the compilation phase, I get 114 errors.

This is my pod file (it's an empty project)

```
#Uncomment the next line to define a global platform for your project 
#platform :ios, '8.0'
target 'mirroir' do
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!
pod 'SideMenuController'
end
```

The install version is 0.1.5

Sorry for my ignorance but I think it's due to my swift version (3.0).

**Comment by Stan92** [comment]
Ok, I think I've found the solution.
I use pod 'SideMenuController',git:'https://github.com/teodorpatras/SideMenuController.git'

**Comment by IvanivOleg** [comment]
@Stan92 you may try to add next lines to your pod file:

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
