### ISSUE TITLE
Is it possible to use SideMenuController as root?

### ISSUE THREAD

**Issue by bitomule** [teodorpatras/SideMenuController#59]
I'm not using storyboards and I set the rootViewController of the window. I've changed it so that rootViewController is SideMenuController but I only get a black window.

Is it possible to use SideMenuController as rootViewController in window?

**Comment by teodorpatras** [comment]
Check out the example project, there you can find a programmatic way of instantiating the `SideMenuController`. You can adapt that to fit your needs.
