### ISSUE TITLE
Show Spinner over centerViewController?

### ISSUE THREAD

**Issue by Ki1L3r** [teodorpatras/SideMenuController#60]
It's possible to show a Spinner over centerController? I'm not able to show it, it only appears if the side menu appears.

**Comment by vyatri** [comment]
I'm currently facing this problem. Has anyone able to give me a hint on how to show a UIView in the middle of the screen over an opened sidebar?

**Comment by Ki1L3r** [comment]
I create it by code. Getting the mainscreen and pulling programatically
