### ISSUE TITLE
In-Call Status Bar moves the view out of the screen instead of resizing

### ISSUE THREAD

**Issue by buechner** [teodorpatras/SideMenuController#65]
![simulator screen shot 29 11 2016 15 26 46](https://cloud.githubusercontent.com/assets/4115196/20713366/4b4c6c7e-b648-11e6-825b-f84ec50eb150.png)
![simulator screen shot 29 11 2016 15 26 40](https://cloud.githubusercontent.com/assets/4115196/20713367/4b70f5e4-b648-11e6-91ae-84a1c4fdd80a.png)

**Comment by piv199** [comment]
![simulator screen shot dec 5 2016 00 40 27](https://cloud.githubusercontent.com/assets/8293191/20869816/7afb045a-ba83-11e6-832a-f930c2cca902.png)

Hm... if side is revealed than we get strange back view at the top...

**Comment by lwinged** [comment]
I don't have this issue with this one :
https://github.com/Friend-LGA/LGSideMenuController

**Comment by teodorpatras** [comment]
I'm sorry for such a late response, but issue has been resolved in release `0.2.2`.
