### ISSUE TITLE
Programmatic creation

### ISSUE THREAD

**Issue by johnrickman** [teodorpatras/SideMenuController#7]
Is it possible to use this programmatically?

I'm try to do so like so

`
 let planDetailsVC = PlanDetailsViewController()
        planDetailsVC.plan = plan
        planDetailsVC.show_members = show_members
        
        let membersVC = PlanMembersViewController()
        membersVC.plan = plan
        
        let controller = SideMenuController()
        controller.addNewController(UINavigationController(rootViewController:planDetailsVC), forSegueType: .Center)
        controller.addNewController(membersVC, forSegueType: .Side)
        
        self.navigationController?.pushViewController(controller, animated: true)
`

But I get error 

> fatal error: unexpectedly found nil while unwrapping an Optional value

for line 402 `let shouldPlaceOnLeftSide = presentationStyle == .UnderCenterPanelLeft || presentationStyle == .AboveCenterPanelLeft`

**Comment by teodorpatras** [comment]
Fixed, now you can do that. Checkout the newly updated Readme file.
