### ISSUE TITLE
viewDidLoad for center view controller called twice

### ISSUE THREAD

**Issue by piv199** [teodorpatras/SideMenuController#72]
I experience the problem when viewDidLoad for UIViewController called twice. I have such structure

SideMenuController -> TabBarController -> NavigationController -> ViewController

Inside SideMenuController I have two viewDidLoad calls. As far as I know, it's not twice, it means that another view controller is loaded and shown...

**Comment by arildojr** [comment]
How did you solve this?
My view controller is being called three times.
