### ISSUE TITLE
Left side sideMenuButton should play nice with existing nav buttons

### ISSUE THREAD

**Issue by mvoccola** [teodorpatras/SideMenuController#74]
**Observations**
The side menu button could play nicer with existing navigation buttons by adding itself to the barButtonItems automatically.

**Improvements**
- The menu button should always be visible in the navigation bar.
- Existing nav bar items, like the back button or custom items, should not be removed when the menu button is added.
- Menu button should always be to the right of the back button and before any other left-side nav item buttons.

**Benefits**
- Menu button is consistently accessible
- Custom implementation is not required for each instance
- Better user experience

**Example**
- Amazon iOS application

![amazon](https://cloud.githubusercontent.com/assets/11658414/21512292/a653e236-cc79-11e6-9258-d7e1e34f84eb.jpg)

**Possible Implementation**
Could be implemented by utilizing `UINavigationController.navigationItem.leftItemsSupplementBackButton = true`

**Comment by teodorpatras** [comment]
Fixed in release `0.2.3`. Now the menu button is appended to the existing items rather than replacing them.
