### ISSUE TITLE
Repeated menu icon

### ISSUE THREAD

**Issue by juanpmarin-infocorp** [teodorpatras/SideMenuController#80]
Hi, how are you ? 
I have an issue with the last version of the lib, the menu icon is getting repeated when I change of ViewController

![2017-01-24](https://cloud.githubusercontent.com/assets/13415603/22267437/c4e0fa84-e251-11e6-874a-000ff5832c99.png)

Thanks !

**Comment by teodorpatras** [comment]
Hey, can you show me the code you use for adding a new controller? And are you adding the menu button by hand?

**Comment by juanpmarin-infocorp** [comment]
Sure, this is the setup

`let contentsView = storyboard?.instantiateViewController(withIdentifier: "categoriesCollection") as! CategoriesCollectionViewController
let contentsNavigation = BaseNavigationController(rootViewController: contentsView)

let tabBarController = UITabBarController()
tabBarController.tabBar.isHidden = true
tabBarController.viewControllers = [communicationsNavigation, channelsNavigation, contentsNavigation]

let sideController = storyboard?.instantiateViewController(withIdentifier: "sideMenuView") as! SideMenuViewController

sideController.items = [
    MenuItem(view: communicationsNavigation, title: "Comunicados", icon: FontAwesome.commentsO),
    MenuItem(view: channelsNavigation, title: "Canales", icon: FontAwesome.rss)
]

if AppSession.appConfig?.content == true {
    sideController.items.append(MenuItem(view: contentsNavigation, title: (AppSession.appConfig?.contentLabel)!, icon: FontAwesome.inbox))
}

sideMenuViewController.embed(sideViewController: sideController)
sideMenuViewController.embed(centerViewController: tabBarController)

[communicationsNavigation, channelsNavigation, contentsNavigation].forEach({ controller in
    controller.addSideMenuButton()
    controller.addSettingsMenuButton()
})`

**Comment by teodorpatras** [comment]
Fixed! Please update to the latest version `0.2.4`.

**Comment by juanpmarin-infocorp** [comment]
Thanks !
