### ISSUE TITLE
SideBarController is not working fine on iphone 7 / iphone 7plus

### ISSUE THREAD

**Issue by haidertbox** [teodorpatras/SideMenuController#86]
The images of iphone 6s and iphone 7 are attached to clear the issue. When the side bar menu comes the other part of other controller shows on the right half screen. But its not a case for iphone 7 device and when the side bar shows on iphone 7 the other half part shows blank area .

I find this issue in my app then tested your sample app and find the issue here as well. 
![screen shot 2017-02-09 at 2 24 58 pm](https://cloud.githubusercontent.com/assets/22466010/22778012/0cfbabe8-eed7-11e6-954f-8a7cf82ffe45.png)

![screen shot 2017-02-09 at 2 26 15 pm](https://cloud.githubusercontent.com/assets/22466010/22778031/211d4096-eed7-11e6-8cbd-8b531a36fba5.png)

**Comment by teodorpatras** [comment]
it only happens for simulators > iPhone 6s
