### ISSUE TITLE
How to manually show side menu?

### ISSUE THREAD

**Issue by Yaldo425** [teodorpatras/SideMenuController#94]
Is it possible to manually show the side menu through a button action? I'm wondering if this is possible since the side menu opens up when you swipe starting from left to right.

**Comment by EngrAhsanAli** [comment]
You can call just  `toggle()` method from `SideMenuController` class or anywhere like         `sideMenuController?.toggle()`.

Also you can check the visibility of side panel through `sidePanelVisible` property in the same way.

Enjoy!
